filebeat.prospectors:
- input_type: log
  paths: [/var/log/service1.log]
  json.keys_under_root: true
  json.overwrite_keys: true

output.logstash:
  hosts: ["192.168.123.10:5044"]
  bulk_max_size: 1024
  template.name: filebeat
  template.path: filebeat.template.json
