#!/bin/sh
### BEGIN INIT INFO
# Provides: elastalert
# Required-Start:	$syslog $local_fs 
# Required-Stop:	$syslog $local_fs 
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Smart mobility parking space lock
### END INIT INFO

. /lib/lsb/init-functions
prog=elastalert
PIDFILE=/var/run/$prog.pid
DESC="Smart mobility parking space lock"
start() {
	log_daemon_msg "Starting $DESC" "$prog"
	start_daemon -p $PIDFILE elasticsearch --rules /etc/elastalert/smartparking.yaml
	if [ $? -ne 0 ]; then
		log_end_msg 1
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_end_msg 0
	fi
	exit 0
}

stop() {
	log_daemon_msg "Stopping $DESC" "$prog"
	killproc -p $PIDFILE elasticsearch
	if [ $? -ne 0 ]; then
		log_end_msg 1
		exit 1
	fi
	if [ $? -eq 0 ]; then
		log_end_msg 0
	fi
}

force_reload() {
	stop
	start

}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	force-reload)
		force_reload
		;;
	restart)
		stop
		start
		;;

	*)
		echo "$Usage: $prog {start|stop|force-reload|restart}"
		exit 2
esac
